CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE lumma.users (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    profile_picture TEXT,
    cover_picture TEXT,
    biography TEXT,
    skill VARCHAR(80),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO lumma.users
(id, name, email, password, active, profile_picture, cover_picture, biography, skill)
VALUES
(gen_random_uuid(),'Elaine Pereira','elaine.pereira2@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Marcelo Lima','marcelo.lima3@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Bianca Teixeira','bianca.teixeira4@email.com',NULL,true,'https://...','https://...','DevOps & IA','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Aline Almeida','aline.almeida5@email.com',NULL,true,'https://...','https://...','SRE Engineer','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Zilda Martins','zilda.martins6@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Marcelo Moreira','marcelo.moreira7@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Monica Costa','monica.costa8@email.com',NULL,true,'https://...','https://...','QA Engineer','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Priscila Gomes','priscila.gomes9@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Camila Reis','camila.reis10@email.com',NULL,true,'https://...','https://...','Tech Lead','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'Clara Soares','clara.soares11@email.com',NULL,false,'https://...','https://...','Desenvolvedor Full-Stack','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Roberto Pereira','roberto.pereira12@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Full-Stack, MERN Stack'),
(gen_random_uuid(),'Sergio Vieira','sergio.vieira13@email.com',NULL,true,'https://...','https://...','SRE Engineer','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Aparecida Martins','aparecida.martins14@email.com',NULL,true,'https://...','https://...','Especialista em Backend','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Cauã Almeida','cauã.almeida15@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Vanessa Alves','vanessa.alves16@email.com',NULL,false,'https://...','https://...','Cientista de Dados','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Elaine Cardoso','elaine.cardoso17@email.com',NULL,true,'https://...','https://...','Tech Lead','Go, gRPC, Docker, Kubernetes'),
(gen_random_uuid(),'Leonardo Campos','leonardo.campos18@email.com',NULL,true,'https://...','https://...','Especialista em Backend','Flutter, Dart, Firebase, REST APIs'),
(gen_random_uuid(),'Roberto Azevedo','roberto.azevedo19@email.com',NULL,false,'https://...','https://...','Arquiteto de Software','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Fernando Fernandes','fernando.fernandes20@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Full-Stack, MERN Stack'),
(gen_random_uuid(),'Helena Rocha','helena.rocha21@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Lucas Rocha','lucas.rocha22@email.com',NULL,true,'https://...','https://...','Cientista de Dados','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Aline Batista','aline.batista23@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','Mobile, React Native, Redux'),
(gen_random_uuid(),'Flavia Andrade','flavia.andrade24@email.com',NULL,true,'https://...','https://...','Product Engineer','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Bruna Lima','bruna.lima25@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Luana Ramos','luana.ramos26@email.com',NULL,false,'https://...','https://...','Desenvolvedor de APIs','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Paulo Almeida','paulo.almeida27@email.com',NULL,false,'https://...','https://...','Consultor de TI','Vue.js, TypeScript, GraphQL, Firebase'),
(gen_random_uuid(),'Camila Sales','camila.sales28@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Alan Costa','alan.costa29@email.com',NULL,true,'https://...','https://...','QA Engineer','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Sabrina Reis','sabrina.reis30@email.com',NULL,true,'https://...','https://...','Product Engineer','Node.js, Express, MongoDB, Docker'),
(gen_random_uuid(),'Sergio Silva','sergio.silva31@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Kaique Castro','kaique.castro32@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Raquel Costa','raquel.costa33@email.com',NULL,true,'https://...','https://...','DevOps & IA','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Otavio Sales','otavio.sales34@email.com',NULL,true,'https://...','https://...','Consultor de TI','Go, gRPC, Docker, Kubernetes'),
(gen_random_uuid(),'Alan Barbosa','alan.barbosa35@email.com',NULL,true,'https://...','https://...','Consultor de TI','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Isabela Cardoso','isabela.cardoso36@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Victor Rocha','victor.rocha37@email.com',NULL,true,'https://...','https://...','DevOps & IA','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Paulo Barbosa','paulo.barbosa38@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Tiago Ferreira','tiago.ferreira39@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Monica Freitas','monica.freitas40@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Cauã Nascimento','cauã.nascimento41@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Ximena Pinto','ximena.pinto42@email.com',NULL,true,'https://...','https://...','Desenvolvedora Mobile','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Jaqueline Barbosa','jaqueline.barbosa43@email.com',NULL,false,'https://...','https://...','Tech Lead','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Pablo Moreira','pablo.moreira44@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'Matheus Dias','matheus.dias45@email.com',NULL,true,'https://...','https://...','Desenvolvedor de APIs','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Bianca Almeida','bianca.almeida46@email.com',NULL,true,'https://...','https://...','Especialista em Backend','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Vanessa Rodrigues','vanessa.rodrigues47@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Mobile, React Native, Redux'),
(gen_random_uuid(),'Beatriz Nunes','beatriz.nunes48@email.com',NULL,false,'https://...','https://...','Cientista de Dados','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Aline Freitas','aline.freitas49@email.com',NULL,false,'https://...','https://...','Desenvolvedor de APIs','Vue.js, TypeScript, GraphQL, Firebase'),
(gen_random_uuid(),'Renata Nascimento','renata.nascimento50@email.com',NULL,true,'https://...','https://...','QA Engineer','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Bruno Alves','bruno.alves51@email.com',NULL,true,'https://...','https://...','QA Engineer','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Jorge Cavalcanti','jorge.cavalcanti52@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Mariana Araujo','mariana.araujo53@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Renata Martins','renata.martins54@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Fernanda Teixeira','fernanda.teixeira55@email.com',NULL,false,'https://...','https://...','Cientista de Dados','Go, gRPC, Docker, Kubernetes'),
(gen_random_uuid(),'Renata Rodrigues','renata.rodrigues56@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Gabriel Castro','gabriel.castro57@email.com',NULL,true,'https://...','https://...','DevOps & IA','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Jose Lopes','jose.lopes58@email.com',NULL,false,'https://...','https://...','QA Engineer','Go, gRPC, Docker, Kubernetes'),
(gen_random_uuid(),'Ursula Carvalho','ursula.carvalho59@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','QA Automation, Selenium, Cypress'),
(gen_random_uuid(),'Leticia Reis','leticia.reis60@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Luis Vieira','luis.vieira61@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Isabela Martins','isabela.martins62@email.com',NULL,true,'https://...','https://...','Desenvolvedora Mobile','Ruby on Rails, PostgreSQL, Heroku'),
(gen_random_uuid(),'Ulisses Tavares','ulisses.tavares63@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Mariana Souza','mariana.souza64@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Mariana Nunes','mariana.nunes65@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Victor Rodrigues','victor.rodrigues66@email.com',NULL,false,'https://...','https://...','Especialista em Segurança','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Amanda Batista','amanda.batista67@email.com',NULL,true,'https://...','https://...','Desenvolvedor de APIs','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Denise Ferreira','denise.ferreira68@email.com',NULL,true,'https://...','https://...','Desenvolvedor de APIs','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Bruna Carvalho','bruna.carvalho69@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Bruna Araujo','bruna.araujo70@email.com',NULL,false,'https://...','https://...','Engenheiro de Machine Learning','Vue.js, TypeScript, GraphQL, Firebase'),
(gen_random_uuid(),'Fabio Sales','fabio.sales71@email.com',NULL,true,'https://...','https://...','Especialista em Backend','Full-Stack, MERN Stack'),
(gen_random_uuid(),'Luis Moura','luis.moura72@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Roberto Carvalho','roberto.carvalho73@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Marcos Rodrigues','marcos.rodrigues74@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Mobile, React Native, Redux'),
(gen_random_uuid(),'Daniel Costa','daniel.costa75@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'William Castro','william.castro76@email.com',NULL,true,'https://...','https://...','DevOps & IA','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Cauã Alves','cauã.alves77@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','Mobile, React Native, Redux'),
(gen_random_uuid(),'Felipe Alves','felipe.alves78@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Carlos Vieira','carlos.vieira79@email.com',NULL,true,'https://...','https://...','Desenvolvedora Mobile','Node.js, Express, MongoDB, Docker'),
(gen_random_uuid(),'Leonardo Duarte','leonardo.duarte80@email.com',NULL,false,'https://...','https://...','Cientista de Dados','Machine Learning, PyTorch, NLP'),
(gen_random_uuid(),'André Souza','andré.souza81@email.com',NULL,true,'https://...','https://...','QA Engineer','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Julia Silva','julia.silva82@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Gustavo Tavares','gustavo.tavares83@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Zilda Silva','zilda.silva84@email.com',NULL,true,'https://...','https://...','Especialista em Backend','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'Yasmin Oliveira','yasmin.oliveira85@email.com',NULL,true,'https://...','https://...','Tech Lead','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Raquel Lima','raquel.lima86@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Julia Monteiro','julia.monteiro87@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Juliana Guimaraes','juliana.guimaraes88@email.com',NULL,true,'https://...','https://...','QA Engineer','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Eduardo Costa','eduardo.costa89@email.com',NULL,false,'https://...','https://...','Arquiteto de Software','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Ana Ribeiro','ana.ribeiro90@email.com',NULL,false,'https://...','https://...','Desenvolvedor Frontend','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Giovanna Tavares','giovanna.tavares91@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Gustavo Farias','gustavo.farias92@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'Miguel Almeida','miguel.almeida93@email.com',NULL,true,'https://...','https://...','Product Engineer','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Debora Almeida','debora.almeida94@email.com',NULL,true,'https://...','https://...','DevOps & IA','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Natalia Dias','natalia.dias95@email.com',NULL,true,'https://...','https://...','Especialista em Backend','Flutter, Dart, Firebase, REST APIs'),
(gen_random_uuid(),'Marcos Castro','marcos.castro96@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Ana Pereira','ana.pereira97@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Mobile, React Native, Redux'),
(gen_random_uuid(),'Ulisses Soares','ulisses.soares98@email.com',NULL,false,'https://...','https://...','Entusiasta de Cloud Computing','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Marcos Azevedo','marcos.azevedo99@email.com',NULL,false,'https://...','https://...','Desenvolvedor Frontend','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Clara Nunes','clara.nunes100@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'André Oliveira','andré.oliveira101@email.com',NULL,true,'https://...','https://...','QA Engineer','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Pablo Freitas','pablo.freitas102@email.com',NULL,true,'https://...','https://...','Desenvolvedora Mobile','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Raquel Rodrigues','raquel.rodrigues103@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Cauã Pereira','cauã.pereira104@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Giovanna Cavalcanti','giovanna.cavalcanti105@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Sergio Lima','sergio.lima106@email.com',NULL,false,'https://...','https://...','QA Engineer','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Davi Tavares','davi.tavares107@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','Mobile, React Native, Redux'),
(gen_random_uuid(),'Natalia Melo','natalia.melo108@email.com',NULL,true,'https://...','https://...','DevOps & IA','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Daniel Carvalho','daniel.carvalho109@email.com',NULL,true,'https://...','https://...','Desenvolvedor de APIs','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Talita Moreira','talita.moreira110@email.com',NULL,false,'https://...','https://...','Desenvolvedora Mobile','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Ivo Costa','ivo.costa111@email.com',NULL,true,'https://...','https://...','Especialista em Backend','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Wanessa Campos','wanessa.campos112@email.com',NULL,true,'https://...','https://...','SRE Engineer','Machine Learning, PyTorch, NLP'),
(gen_random_uuid(),'Camila Sales','camila.sales113@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Patricia Gomes','patricia.gomes114@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Miguel Moura','miguel.moura115@email.com',NULL,false,'https://...','https://...','Especialista em Backend','QA Automation, Selenium, Cypress'),
(gen_random_uuid(),'Vitoria Cunha','vitoria.cunha116@email.com',NULL,false,'https://...','https://...','Desenvolvedora Mobile','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Viviane Araujo','viviane.araujo117@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Jose Guimaraes','jose.guimaraes118@email.com',NULL,false,'https://...','https://...','Entusiasta de Cloud Computing','Mobile, React Native, Redux'),
(gen_random_uuid(),'Marcelo Ribeiro','marcelo.ribeiro119@email.com',NULL,false,'https://...','https://...','Consultor de TI','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Gabriel Melo','gabriel.melo120@email.com',NULL,false,'https://...','https://...','Entusiasta de Cloud Computing','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Fernanda Correia','fernanda.correia121@email.com',NULL,true,'https://...','https://...','Consultor de TI','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Jose Moreira','jose.moreira122@email.com',NULL,false,'https://...','https://...','Consultor de TI','Node.js, Express, MongoDB, Docker'),
(gen_random_uuid(),'Sergio Moreira','sergio.moreira123@email.com',NULL,false,'https://...','https://...','Arquiteto de Software','Mobile, React Native, Redux'),
(gen_random_uuid(),'Sandra Soares','sandra.soares124@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Kaique Guimaraes','kaique.guimaraes125@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Priscila Moreira','priscila.moreira126@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Carlos Dias','carlos.dias127@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Fernanda Gomes','fernanda.gomes128@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Gael Carvalho','gael.carvalho129@email.com',NULL,false,'https://...','https://...','QA Engineer','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Alexandre Freitas','alexandre.freitas130@email.com',NULL,true,'https://...','https://...','QA Engineer','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Leonardo Cavalcanti','leonardo.cavalcanti131@email.com',NULL,true,'https://...','https://...','Desenvolvedor de APIs','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Monica Batista','monica.batista132@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Juliana Barbosa','juliana.barbosa133@email.com',NULL,false,'https://...','https://...','Especialista em Microsserviços','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Roberto Tavares','roberto.tavares134@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Nicolas Almeida','nicolas.almeida135@email.com',NULL,false,'https://...','https://...','QA Engineer','Flutter, Dart, Firebase, REST APIs'),
(gen_random_uuid(),'Ana Reis','ana.reis136@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Talita Lima','talita.lima137@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Node.js, Express, MongoDB, Docker'),
(gen_random_uuid(),'Henrique Ramos','henrique.ramos138@email.com',NULL,true,'https://...','https://...','DevOps & IA','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Bernardo Teixeira','bernardo.teixeira139@email.com',NULL,true,'https://...','https://...','Product Engineer','Vue.js, TypeScript, GraphQL, Firebase'),
(gen_random_uuid(),'Gabriel Soares','gabriel.soares140@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Luis Rocha','luis.rocha141@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Jose Cavalcanti','jose.cavalcanti142@email.com',NULL,false,'https://...','https://...','Especialista em Backend','Flutter, Dart, Firebase, REST APIs'),
(gen_random_uuid(),'Pedro Tavares','pedro.tavares143@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Marcelo Castro','marcelo.castro144@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Renata Martins','renata.martins145@email.com',NULL,true,'https://...','https://...','DevOps & IA','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Eduardo Lima','eduardo.lima146@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Talita Farias','talita.farias147@email.com',NULL,true,'https://...','https://...','Tech Lead','Flutter, Dart, Firebase, REST APIs'),
(gen_random_uuid(),'Clara Pinto','clara.pinto148@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Debora Alves','debora.alves149@email.com',NULL,true,'https://...','https://...','DevOps & IA','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Aparecida Duarte','aparecida.duarte150@email.com',NULL,false,'https://...','https://...','Especialista em Microsserviços','Full-Stack, MERN Stack'),
(gen_random_uuid(),'Jaqueline Martins','jaqueline.martins151@email.com',NULL,true,'https://...','https://...','Desenvolvedor de APIs','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Larissa Farias','larissa.farias152@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Tiago Oliveira','tiago.oliveira153@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','Data Science, Python, Pandas, TensorFlow'),
(gen_random_uuid(),'Cauã Cardoso','cauã.cardoso154@email.com',NULL,true,'https://...','https://...','Consultor de TI','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Maria Cavalcanti','maria.cavalcanti155@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Raquel Cardoso','raquel.cardoso156@email.com',NULL,true,'https://...','https://...','Product Engineer','Machine Learning, PyTorch, NLP'),
(gen_random_uuid(),'Raquel Ribeiro','raquel.ribeiro157@email.com',NULL,true,'https://...','https://...','Consultor de TI','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'William Freitas','william.freitas158@email.com',NULL,false,'https://...','https://...','Desenvolvedora de Jogos','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Raquel Azevedo','raquel.azevedo159@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Renata Ferreira','renata.ferreira160@email.com',NULL,true,'https://...','https://...','Product Engineer','Flutter, Dart, Firebase, REST APIs'),
(gen_random_uuid(),'Jose Correia','jose.correia161@email.com',NULL,false,'https://...','https://...','SRE Engineer','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Cristina Santos','cristina.santos162@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Nicolas Carvalho','nicolas.carvalho163@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Data Science, Python, Pandas, TensorFlow'),
(gen_random_uuid(),'Priscila Pinto','priscila.pinto164@email.com',NULL,true,'https://...','https://...','Cientista de Dados','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Pablo Martins','pablo.martins165@email.com',NULL,false,'https://...','https://...','Especialista em Segurança','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Nicolas Melo','nicolas.melo166@email.com',NULL,false,'https://...','https://...','Especialista em Segurança','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Bernardo Xavier','bernardo.xavier167@email.com',NULL,true,'https://...','https://...','Product Engineer','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Camila Vieira','camila.vieira168@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Debora Campos','debora.campos169@email.com',NULL,false,'https://...','https://...','Tech Lead','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Sergio Machado','sergio.machado170@email.com',NULL,true,'https://...','https://...','QA Engineer','Data Science, Python, Pandas, TensorFlow'),
(gen_random_uuid(),'Juliana Farias','juliana.farias171@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'André Almeida','andré.almeida172@email.com',NULL,true,'https://...','https://...','Desenvolvedora Mobile','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'Amanda Tavares','amanda.tavares173@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Aline Tavares','aline.tavares174@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Bruno Martins','bruno.martins175@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Ruby on Rails, PostgreSQL, Heroku'),
(gen_random_uuid(),'Rodrigo Barbosa','rodrigo.barbosa176@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Priscila Oliveira','priscila.oliveira177@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Ingrid Lima','ingrid.lima178@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','Machine Learning, PyTorch, NLP'),
(gen_random_uuid(),'Maria Batista','maria.batista179@email.com',NULL,false,'https://...','https://...','Desenvolvedora de Jogos','Ruby on Rails, PostgreSQL, Heroku'),
(gen_random_uuid(),'Kevin Dias','kevin.dias180@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Go, gRPC, Docker, Kubernetes'),
(gen_random_uuid(),'Ursula Pereira','ursula.pereira181@email.com',NULL,false,'https://...','https://...','Especialista em Backend','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Nicolas Rodrigues','nicolas.rodrigues182@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Isabela Batista','isabela.batista183@email.com',NULL,true,'https://...','https://...','Especialista em Backend','Ruby on Rails, PostgreSQL, Heroku'),
(gen_random_uuid(),'Amanda Melo','amanda.melo184@email.com',NULL,true,'https://...','https://...','QA Engineer','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Nadia Machado','nadia.machado185@email.com',NULL,false,'https://...','https://...','Product Engineer','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Ricardo Ramos','ricardo.ramos186@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','React Native, Expo, GraphQL'),
(gen_random_uuid(),'William Tavares','william.tavares187@email.com',NULL,true,'https://...','https://...','Desenvolvedora Mobile','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'Bruna Campos','bruna.campos188@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Rodrigo Melo','rodrigo.melo189@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Igor Moreira','igor.moreira190@email.com',NULL,false,'https://...','https://...','SRE Engineer','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Tatiane Oliveira','tatiane.oliveira191@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Ingrid Correia','ingrid.correia192@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Alan Ramos','alan.ramos193@email.com',NULL,false,'https://...','https://...','Desenvolvedora Mobile','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Felipe Freitas','felipe.freitas194@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Thiago Rodrigues','thiago.rodrigues195@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Victor Tavares','victor.tavares196@email.com',NULL,true,'https://...','https://...','Desenvolvedor de APIs','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Kevin Pereira','kevin.pereira197@email.com',NULL,false,'https://...','https://...','Engenheiro de Machine Learning','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Carlos Nunes','carlos.nunes198@email.com',NULL,false,'https://...','https://...','Desenvolvedora de Jogos','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Rafael Pinto','rafael.pinto199@email.com',NULL,true,'https://...','https://...','QA Engineer','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Clara Soares','clara.soares200@email.com',NULL,true,'https://...','https://...','Especialista em Backend','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Davi Batista','davi.batista201@email.com',NULL,true,'https://...','https://...','DevOps & IA','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Aparecida Oliveira','aparecida.oliveira202@email.com',NULL,false,'https://...','https://...','Arquiteto de Software','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Pablo Castro','pablo.castro203@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Ulisses Teixeira','ulisses.teixeira204@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','Machine Learning, PyTorch, NLP'),
(gen_random_uuid(),'Miguel Monteiro','miguel.monteiro205@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Giovanna Alves','giovanna.alves206@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','QA Automation, Selenium, Cypress'),
(gen_random_uuid(),'Igor Farias','igor.farias207@email.com',NULL,false,'https://...','https://...','Engenheiro de Machine Learning','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Monica Melo','monica.melo208@email.com',NULL,true,'https://...','https://...','Product Engineer','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Fabio Soares','fabio.soares209@email.com',NULL,false,'https://...','https://...','Entusiasta de Cloud Computing','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Wanessa Silva','wanessa.silva210@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Igor Souza','igor.souza211@email.com',NULL,true,'https://...','https://...','Consultor de TI','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Denise Sales','denise.sales212@email.com',NULL,true,'https://...','https://...','Product Engineer','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Leonardo Fernandes','leonardo.fernandes213@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Kevin Farias','kevin.farias214@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Alan Pinto','alan.pinto215@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Debora Melo','debora.melo216@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Camila Almeida','camila.almeida217@email.com',NULL,false,'https://...','https://...','Entusiasta de Cloud Computing','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Amanda Castro','amanda.castro218@email.com',NULL,false,'https://...','https://...','Engenheira de Dados','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Jaqueline Vieira','jaqueline.vieira219@email.com',NULL,false,'https://...','https://...','Cientista de Dados','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Ursula Nascimento','ursula.nascimento220@email.com',NULL,true,'https://...','https://...','Product Engineer','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Sabrina Martins','sabrina.martins221@email.com',NULL,true,'https://...','https://...','SRE Engineer','Full-Stack, MERN Stack'),
(gen_random_uuid(),'Matheus Fernandes','matheus.fernandes222@email.com',NULL,true,'https://...','https://...','QA Engineer','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Otavio Fernandes','otavio.fernandes223@email.com',NULL,true,'https://...','https://...','DevOps & IA','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Heitor Barbosa','heitor.barbosa224@email.com',NULL,false,'https://...','https://...','Desenvolvedor de APIs','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Isabela Moreira','isabela.moreira225@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Alexandre Melo','alexandre.melo226@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Luis Rocha','luis.rocha227@email.com',NULL,true,'https://...','https://...','Desenvolvedora Mobile','QA Automation, Selenium, Cypress'),
(gen_random_uuid(),'Aparecida Reis','aparecida.reis228@email.com',NULL,true,'https://...','https://...','QA Engineer','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Fabio Tavares','fabio.tavares229@email.com',NULL,false,'https://...','https://...','Especialista em Microsserviços','Elixir, Phoenix, PostgreSQL'),
(gen_random_uuid(),'Cauã Castro','cauã.castro230@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','Vue.js, TypeScript, GraphQL, Firebase'),
(gen_random_uuid(),'Diego Nunes','diego.nunes231@email.com',NULL,true,'https://...','https://...','Desenvolvedor Frontend','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Kevin Alves','kevin.alves232@email.com',NULL,true,'https://...','https://...','Product Engineer','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Heitor Gomes','heitor.gomes233@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Miguel Soares','miguel.soares234@email.com',NULL,false,'https://...','https://...','SRE Engineer','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Flavia Ferreira','flavia.ferreira235@email.com',NULL,false,'https://...','https://...','Desenvolvedor Frontend','QA Automation, Selenium, Cypress'),
(gen_random_uuid(),'Fabio Cunha','fabio.cunha236@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Denise Rodrigues','denise.rodrigues237@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Luana Ferreira','luana.ferreira238@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Kevin Costa','kevin.costa239@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Julia Rocha','julia.rocha240@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Juliana Cardoso','juliana.cardoso241@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Ximena Cavalcanti','ximena.cavalcanti242@email.com',NULL,true,'https://...','https://...','Arquiteto de Software','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Rodrigo Ferreira','rodrigo.ferreira243@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Node.js, Express, MongoDB, Docker'),
(gen_random_uuid(),'Viviane Ramos','viviane.ramos244@email.com',NULL,false,'https://...','https://...','Especialista em Segurança','Vue.js, TypeScript, GraphQL, Firebase'),
(gen_random_uuid(),'Elaine Soares','elaine.soares245@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Scala, Akka, Apache Spark, Kafka'),
(gen_random_uuid(),'Talita Vieira','talita.vieira246@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Beatriz Moreira','beatriz.moreira247@email.com',NULL,true,'https://...','https://...','Desenvolvedor de APIs','Data Science, Python, Pandas, TensorFlow'),
(gen_random_uuid(),'Elaine Teixeira','elaine.teixeira248@email.com',NULL,false,'https://...','https://...','Cientista de Dados','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Ricardo Martins','ricardo.martins249@email.com',NULL,true,'https://...','https://...','Desenvolvedora de Jogos','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Eduardo Reis','eduardo.reis250@email.com',NULL,true,'https://...','https://...','Tech Lead','Rust, WebAssembly, Actix'),
(gen_random_uuid(),'Ingrid Vieira','ingrid.vieira251@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Maria Batista','maria.batista252@email.com',NULL,false,'https://...','https://...','Desenvolvedor Full-Stack','QA Automation, Selenium, Cypress'),
(gen_random_uuid(),'Daniel Guimaraes','daniel.guimaraes253@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Marcelo Cunha','marcelo.cunha254@email.com',NULL,true,'https://...','https://...','SRE Engineer','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Davi Sales','davi.sales255@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Alan Castro','alan.castro256@email.com',NULL,false,'https://...','https://...','Engenheiro de Machine Learning','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Lucas Ramos','lucas.ramos257@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','Data Science, Python, Pandas, TensorFlow'),
(gen_random_uuid(),'Tatiane Rocha','tatiane.rocha258@email.com',NULL,true,'https://...','https://...','QA Engineer','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Patricia Lima','patricia.lima259@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Ximena Nunes','ximena.nunes260@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Full-Stack, MERN Stack'),
(gen_random_uuid(),'André Nascimento','andré.nascimento261@email.com',NULL,true,'https://...','https://...','Engenheiro de Machine Learning','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Felipe Correia','felipe.correia262@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','Python, Django, PostgreSQL, AWS'),
(gen_random_uuid(),'Davi Azevedo','davi.azevedo263@email.com',NULL,true,'https://...','https://...','Especialista em Microsserviços','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Camila Araujo','camila.araujo264@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Spring-Boot, Angular, Kubernetes, Apache Kafka'),
(gen_random_uuid(),'Luis Cardoso','luis.cardoso265@email.com',NULL,false,'https://...','https://...','Cientista de Dados','Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Elaine Cardoso','elaine.cardoso266@email.com',NULL,false,'https://...','https://...','Especialista em Segurança','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'Ana Moura','ana.moura267@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Mobile, React Native, Redux'),
(gen_random_uuid(),'William Almeida','william.almeida268@email.com',NULL,false,'https://...','https://...','Especialista em Backend','Machine Learning, PyTorch, NLP'),
(gen_random_uuid(),'Ingrid Barbosa','ingrid.barbosa269@email.com',NULL,true,'https://...','https://...','QA Engineer','Machine Learning, PyTorch, NLP'),
(gen_random_uuid(),'Fernanda Oliveira','fernanda.oliveira270@email.com',NULL,false,'https://...','https://...','Engenheiro de Machine Learning','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Felipe Alves','felipe.alves271@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Sabrina Correia','sabrina.correia272@email.com',NULL,false,'https://...','https://...','Especialista em Bancos de Dados','Data Science, Python, Pandas, TensorFlow'),
(gen_random_uuid(),'Bianca Tavares','bianca.tavares273@email.com',NULL,false,'https://...','https://...','Engenheira de Dados','Frontend, Next.js, Tailwind CSS'),
(gen_random_uuid(),'Flavia Alves','flavia.alves274@email.com',NULL,false,'https://...','https://...','Desenvolvedora de Jogos','Blockchain, Solidity, Web3.js'),
(gen_random_uuid(),'Priscila Oliveira','priscila.oliveira275@email.com',NULL,true,'https://...','https://...','Tech Lead','SRE, Prometheus, Grafana, Kubernetes'),
(gen_random_uuid(),'Kevin Moreira','kevin.moreira276@email.com',NULL,true,'https://...','https://...','Tech Lead','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Helena Cardoso','helena.cardoso277@email.com',NULL,true,'https://...','https://...','Tech Lead','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Henrique Fernandes','henrique.fernandes278@email.com',NULL,false,'https://...','https://...','Entusiasta de Cloud Computing','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Camila Campos','camila.campos279@email.com',NULL,true,'https://...','https://...','SRE Engineer','PHP, Laravel, MySQL, Vue.js'),
(gen_random_uuid(),'Gabriel Dias','gabriel.dias280@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Matheus Sales','matheus.sales281@email.com',NULL,true,'https://...','https://...','Desenvolvedora Mobile','Kotlin, Android, Jetpack Compose'),
(gen_random_uuid(),'Vanessa Dias','vanessa.dias282@email.com',NULL,true,'https://...','https://...','Engenheira de Dados','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Priscila Gomes','priscila.gomes283@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Vue.js, TypeScript, GraphQL, Firebase'),
(gen_random_uuid(), 'Rodrigo Pereira', 'rodrigo.pereira284@email.com', NULL, true, 'https://...', 'https://...', 'DevOps & IA', 'Cybersecurity, Pentest, OWASP'),
(gen_random_uuid(),'Maria Monteiro','maria.monteiro285@email.com',NULL,true,'https://...','https://...','Especialista em Segurança','Data Engineering, Airflow, BigQuery'),
(gen_random_uuid(),'Pedro Ribeiro','pedro.ribeiro286@email.com',NULL,true,'https://...','https://...','Desenvolvedor Full-Stack','Flutter, Dart, Firebase, REST APIs'),
(gen_random_uuid(),'Ivo Cavalcanti','ivo.cavalcanti287@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Miguel Moreira','miguel.moreira288@email.com',NULL,true,'https://...','https://...','Tech Lead','Backend, Spring Cloud, RabbitMQ'),
(gen_random_uuid(),'Sandra Nunes','sandra.nunes289@email.com',NULL,true,'https://...','https://...','SRE Engineer','C#, .NET Core, Azure, SQL Server'),
(gen_random_uuid(),'Karina Campos','karina.campos290@email.com',NULL,false,'https://...','https://...','Engenheiro de Machine Learning','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Bernardo Santos','bernardo.santos291@email.com',NULL,false,'https://...','https://...','Desenvolvedora de Jogos','React, Node.js, MongoDB, Docker'),
(gen_random_uuid(),'Jorge Duarte','jorge.duarte292@email.com',NULL,false,'https://...','https://...','Desenvolvedora de Jogos','Java, Hibernate, Microservices, Redis'),
(gen_random_uuid(),'Beatriz Ferreira','beatriz.ferreira293@email.com',NULL,true,'https://...','https://...','SRE Engineer','Angular, RxJS, NestJS, TypeScript'),
(gen_random_uuid(),'Matheus Lima','matheus.lima294@email.com',NULL,true,'https://...','https://...','SRE Engineer','Flutter, Dart, Firebase, REST APIs'),
(gen_random_uuid(),'Fernando Pinto','fernando.pinto295@email.com',NULL,false,'https://...','https://...','Engenheiro de Machine Learning','Swift, iOS, Core Data, SwiftUI'),
(gen_random_uuid(),'Otavio Pinto','otavio.pinto296@email.com',NULL,true,'https://...','https://...','Entusiasta de Cloud Computing','React Native, Expo, GraphQL'),
(gen_random_uuid(),'Flavia Castro','flavia.castro297@email.com',NULL,true,'https://...','https://...','Especialista em Bancos de Dados','Mobile, React Native, Redux'),
(gen_random_uuid(),'Raquel Moreira','raquel.moreira298@email.com',NULL,false,'https://...','https://...','Especialista em Segurança','Mobile, React Native, Redux'),
(gen_random_uuid(),'Cristina Correia','cristina.correia299@email.com',NULL,true,'https://...','https://...','QA Engineer','DevOps, Terraform, Jenkins, AWS'),
(gen_random_uuid(),'Fabio Teixeira','fabio.teixeira300@email.com',NULL,true,'https://...','https://...','Cientista de Dados','Angular, RxJS, NestJS, TypeScript');