spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/lumma
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: lumma
        format_sql: true

  flyway:
    enabled: true
    schemas: lumma
    default_schema: lumma
    locations: classpath:db/migration

server:
  port: 8080