services:

  postgres:
    image: postgres:17

    container_name: lumma-postgres

    environment:
      POSTGRES_DB: lumma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "8080:8080"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: